
services:
  piveau-consus-importing-rdf:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-rdf:1.8.9
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m
      #- PIVEAU_PIPE_LOG_LEVEL=TRACE
      - OTEL_SDK_DISABLED=true

  piveau-consus-importing-ckan:
    image: registry.gitlab.com/piveau/consus/piveau-consus-importing-ckan:1.2.7
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m

  piveau-consus-transforming-js:
    image: registry.gitlab.com/piveau/consus/piveau-consus-transforming-js:4.0.1
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m
    volumes:
      - ./piveau_scripts:/usr/verticles/scripts

  piveau-consus-exporting-hub:
    image: registry.gitlab.com/piveau/consus/piveau-consus-exporting-hub:5.0.2
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx1g
      - PIVEAU_HUB_APIKEY=yourRepoApiKey
      #- PIVEAU_PIPE_LOG_LEVEL=TRACE
      - OTEL_SDK_DISABLED=true

  piveau-consus-scheduling:
    image: registry.gitlab.com/piveau/consus/piveau-consus-scheduling:3.0.1
    logging:
      options:
        max-size: "50m"
    ports:
      - '8090:8080'
      - '8095:8085'
      - '5000:5000'
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
      #- PIVEAU_PIPE_LOG_LEVEL=TRACE
      - OTEL_SDK_DISABLED=true
    volumes:
      - ./piveau_pipes:/usr/verticles/pipes

  piveau-consus-importing-csw:
      build: piveau_modules/piveau-consus-importing-csw
      image: piveau/piveau-consus-importing-csw:local-build
      logging:
        options:
          max-size: "50m"
      environment:
        - JAVA_OPTS=-Xms200m -Xmx500m
        #- PIVEAU_PIPE_LOG_LEVEL=TRACE
        - OTEL_SDK_DISABLED=true
