# Manual mapping between CKAN organization ids and I14Y slugs.
# This manually curated mapping becomes obsolete, when I14Y itself provides the mapping back to CKAN organization id.
# In the meantime, this mapping can be manually extended when necessary.
CKAN_TO_I14Y_ORG_MAPPING: dict[str, str] = {
    "abteilung-uebertragbare-krankheiten": "abteilung-uebertragbare-krankheiten",
    "ag": "ch-kt-ag",
    "agroscope": "ch-agroscope",
    "bernmobil": "bernmobil",
    "biel-bienne": "ch-gde-biel-bienne",
    "bkb": "ch-bkb",
    "bundesamt-fur-gesundheit-bag": "ch-bag",
    "bundesamt-fur-bevolkerungsschutz-babs": "ch-babs",
    "bundesamt-fur-energie-bfe": "ch-bfe",
    "bundesamt-fur-kommunikation-bakom": "ch-bakom",
    "bundesamt-fur-kultur-bak": "ch-bak",
    "bundesamt-fur-landestopografie-swisstopo": "ch-swisstopo",
    "bundesamt-fur-landwirtschaft-blw": "ch-blw",
    "bundesamt-fur-meteorologie-und-klimatologie-meteoschweiz": "ch-meteoschweiz",
    "bundesamt-fur-raumentwicklung-are": "ch-are",
    "bundesamt-fur-statistik-bfs": "ch1",
    "bundesamt-fur-strassen-astra": "ch-astra",
    "bundesamt-fur-umwelt-bafu": "ch-bafu",
    "bundesamt-fur-verkehr-bav": "ch-bav",
    "bundesamt-fur-zivildienst-zivi": "ch-zivi",
    "bundesamt-fur-zivilluftfahrt-bazl": "ch-bazl",
    "eidgenossische-finanzverwaltung-efv": "ch-efv",
    "eidgenoessische_zollverwaltung_ezv": "ch-bazg",
    "elcom": "ch-elcom",
    "fondation-modus": "ch-ge-fondationmodus",
    "gruppe-verteidigung": "ch-vtg",
    "identitas": "ch-identitas",
    "kanton-bern-2": "ch-kt-bern",
    "kanton-basel-landschaft": "ch-kt-bl",
    "kanton-basel-stadt": "ch-kt-bs",
    "kanton-st-gallen": "ch-kt-st-gallen",
    "lustat": "ch-lustat",
    "dienst-ueberwachung-post-und-fernmeldeverkehr-uepf": "ch-uepf",
    "direktion-fur-entwicklung-und-zusammenarbeit-deza": "ch-deza",
    "eth-bibliothek": "ch-eth-lib",
    "eth-zuerich": "ch-eth",
    "gemeinde_emmen": "ch-gde-emmen",
    "gemeinde_koeniz": "ch-gde-koeniz",
    "kanton-graubuenden": "ch-kt-gr",
    "kanton-schaffhausen": "ch-kt-sh",
    "kanton-schwyz": "ch-kt-sz",
    "kanton-thurgau": "ch-kt-tg",
    "kanton-uri": "ch-kt-uri",
    "kanton-zuerich": "ch-kt-zh",
    "swissmedic": "ch-swissmedic",
    "kanton_freiburg": "ch-kt-fr",
    "kanton_solothurn": "ch-kt-so",
    "lausanne": "ch-gde-lausanne",
    "morges": "ch-gde-morges",
    "public-sector-transformation": "ch-bfh-ipst",
    "sbfi": "ch-sbfi",
    "schweizerische-bundesbahnen-sbb": "ch-sbb",
    "schweizerische-nationalbibliothek-nb": "ch-nabibl",
    "schweizerisches-bundesarchiv-bar": "ch-bar",
    "swiss-emobility": "ch-swiss-emobility",
    "schweizerisches-nationalmuseum-snm": "ch-snm",
    "staatssekretariat-fuer-migration-sem": "ch-sem",
    "stadt-bern": "ch-gde-bern",
    "stadt-luzern": "ch-gde-luzern",
    "stadt-uster": "ch-gde-uster",
    "stadt-winterthur": "ch-gde-winterthur",
    "stadt-zug": "ch-gde-zug",
    "stadt-zurich": "ch-gde-zurich",
    "ti": "ch-kt-ti",
    "ville-geneve": "ch-gde-geneve",
    "canton-du-jura": "ch-kt-ju",
    "canton-geneve": "ch-kt-ge",
    "amt-geoinformation-kanton-schaffhausen": "ch-kt-sh-v-geo",
    "bibliothek-am-guisanplatz-big": "ch-vbs-gs-vbs-big",
    "bildungsstatistik-kanton-zuerich": "ch-kt-zh-edu-stat",
    "bundesamt-fur-lebensmittelsicherheit-und-veterinaerwesen-blv": "ch-blv",
    "bundesamt-fur-wirtschaftliche-landesversorgung-bwl": "ch-bwl",
    "bundesamt_fuer_justiz": "ch-bj",
    "canton-du-valais-cc-geo": "ch-kt-vs-geo",
    "chancellerie-etat-geneve": "ch-kt-ge-chancellerie",
    "dienstzweig-geomatik-gemeinde-koeniz": "ch-gde-koeniz-geomatik",
    "digitale_medien_der_armee_dma": "ch-vbs-v-dma",
    "direktionsbereich-kranken-und-unfallversicherung": "ch-bag-dku",
    "efk": "ch-efk",
    "eidgenoessisches_amt_fuer_das_handelsregister_ehra": "ch-ehra",
    "ekz": "ch-kt-zh-ekz",
    "fachstelle-geoinformation-des-kantons-glarus": "ch-kt-gl-bau-geo",
    "fachstelle-ogd-kanton-zuerich": "ch-kt-zh-jus-stat-ogd",
    "finanzmarktaufsicht-fl": "fl-finanzmarkt",
    "finanzverwaltung-der-stadt-bern": "ch-gde-bern-finanzverwaltung",
    "gemeindeamt-kanton-zuerich": "ch-kt-zh-jus-gemeinden",
    "geoinformation-der-stadt-bern": "ch-gde-bern-geoinformation",
    "geoinformation-kanton-zuerich": "ch-kt-zh-are-geo",
    "geoinformation-kt-gr": "ch-kt-gr-alg-geo",
    "geoinformation_kanton_freiburg": "ch-kt-fr-geo",
    "handelsregisteramt-kanton-zuerich": "ch-kt-zh-jus-handelsregister",
    "hes-so-geneve": "ch-edu-ge-hes",
    "ima-kanton-zuerich": "ch-kt-zh-bd-ima",
    "imad-ge": "ch-kt-ge-imad",
    "immobilien-stadt-bern": "ch-gde-bern-immobilien",
    "infrastruktur-mobilitaet-biel-bienne": "ch-gde-biel-bienne-infrastruktur",
    "kanton-wallis": "ch-kt-wallis",
    "kanton-zug": "ch-kt-zug",
    "kantonspolizei-kanton-zuerich": "ch-kt-zh-pol",
    "liechtenstein": "fl",
    "oberjugendanwaltschaft-kanton-zuerich": "ch-kt-zh-oberjugendanwaltschaft",
    "parlamentsdienste-pd": "ch-pd",
    "personalamt-kanton-zuerich": "ch-kt-zh-personalamt",
    "psi": "ch-edu-psi",
    "schweizerischer-nationalfonds-zur-forderung-der-wissenschaftlichen-forschung-snf": "ch-snf",
    "ssd": "ch-kt-fr-sda",
    "staatsarchiv-kanton-zuerich": "ch-kt-zh-jus-staatsarchiv",
    "staatskanzlei-glarus": "ch-kt-gl-staatskanzlei",
    "staatskanzlei-kanton-zuerich": "ch-kt-zh-staatskanzlei",
    "staatskanzlei-zug": "ch-kt-zg-staatskanzlei",
    "stadt-st-gallen": "ch-gde-st-gallen",
    "stadtarchiv-bern": "ch-gde-bern-stadtarchiv",
    "standeskanzlei-graubuenden": "ch-kt-gr-standeskanzlei",
    "statistik-stadt-bern": "ch-gde-bern-statistik",
    "statistisches-amt-kanton-zuerich": "ch-kt-zh-jus-stat",
    "tiefbauamt-kanton-zuerich": "ch-kt-zh-bau-tiefbau",
    "volksschulamt-kanton-zuerich": "ch-kt-zh-bildung-volksschule",
    "wsl": "ch-wsl",
    "zb_zuerich": "ch-kt-zh-zb",
}


def resolve_i14y_publisher_slug(
    ckan_org_id: str | None,
) -> str | None:
    """
    Resolves CKAN organization ids to I14Y organization slugs.

    Resolution strategy:
    1) Manual mapping table (CKAN_TO_I14Y_ORG_MAPPING)
    """
    if ckan_org_id and ckan_org_id in CKAN_TO_I14Y_ORG_MAPPING:
        return CKAN_TO_I14Y_ORG_MAPPING[ckan_org_id]

    return None
