# Uncomment for local development
# local_backend: true

backend:
  name: gitlab
  repo: docker/lindas-next-piveau-js
  auth_type: pkce
  app_id: your-app-id # TODO: Application ID from your GitLab settings
  api_root: https://gitlab.zazuko.com/api/v4
  base_url: https://gitlab.zazuko.com
  auth_endpoint: oauth/authorize

# These lines should *not* be indented
media_folder: "public/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

i18n:
  structure: multiple_files
  default_locale: de
  locales: [de, fr, it, en]

collections:
  - name: handbook-section
    label: "Handbook sections"
    label_singular: Handbook section
    folder: "content/sections"
    extension: md
    widget: "list"
    create: true
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
      - name: body
        label: Body
        widget: markdown
        i18n: true
  - name: handbook
    label: "Handbook articles"
    label_singular: Handbook article
    identifier_field: id
    folder: "content/handbook"
    extension: md
    widget: "list"
    create: true
    i18n: true
    summary: "{{title}}"
    view_groups:
      - label: Section
        field: section
    path: '{{section}}/{{slug}}'
    fields:
      - label: Section
        name: section
        widget: relation
        collection: handbook-section
        search_fields: ["title"]
        value_field: title
        required: true
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
      - label: Breadcrumb title
        name: breadcrumb_title
        widget: string
        required: false
        i18n: true
      - label: Permalink
        name: permalink
        widget: string
        i18n: duplicate
        pattern: ["^[a-z0-9]+(?:/[a-z0-9-]+)*$", "Permalink must be lowercase and can only contain letters, numbers, slashes, and hyphens."]
      - name: body
        label: Body
        widget: markdown
        i18n: true
  - name: pages
    label: "Pages"
    folder: "content/pages"
    extension: md
    widget: "list"
    create: false
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
      - label: Heading
        name: heading
        widget: string
        i18n: true
        required: false
      - label: Description
        name: description
        widget: markdown
        i18n: true
      - name: body
        label: Body
        widget: markdown
        i18n: true
  - name: blog
    label: Blog
    label_singular: Blog Post
    folder: "content/blog"
    extension: md
    widget: "list"
    create: true
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
      - label: Slug
        name: slug
        widget: string
        i18n: false
        required: false
        pattern: ["^[a-z0-9]+(?:/[a-z0-9-]+)*$", "Permalink must be lowercase and can only contain letters, numbers, slashes, and hyphens."]
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
        default: "{{now}}"
      - name: subHeading
        label: Subheading
        widget: markdown
        i18n: true
      - name: body
        label: Body
        widget: markdown
        i18n: true
