package swiss.opendata.piveau.testbench;

/**
 * Defines specific goals or states that can be achieved during testing.
 * The GlobalTestRunner uses this to build a dependency graph.
 */
public enum Goal {

    // Hub Initialization
    PROFILE_LOADED, HUB_STARTED,

    // Vocabularies
    BUILTIN_VOCABS_INSTALLED, BUILTIN_XML_VOCABS_INSTALLED, CUSTOM_ODSN_VOCABS_INSTALLED,

    HUB_READY,

    // Organization Operations
    SIMPLE_ORGANIZATION_CREATED, SIMPLE_ORGANIZATION_INDEXED, SIMPLE_ORGANIZATION_UPDATED, SIMPLE_ORGANIZATION_INDEX_UPDATED, SIMPLE_ORGANIZATION_DELETED, SIMPLE_ORGANIZATION_INDEX_DELETED, ODSN_ORGANIZATION_CREATED, ODSN_ORGANIZATION_INDEXED, ODSN_ORGANIZATION_UPDATED, ODSN_ORGANIZATION_INDEX_UPDATED, ODSN_ORGANIZATION_DELETED, ODSN_ORGANIZATION_INDEX_DELETED,

    // Catalog Operations
    SIMPLE_CATALOG_CREATED, SIMPLE_CATALOG_INDEXED, SIMPLE_CATALOG_UPDATED, SIMPLE_CATALOG_INDEX_UPDATED, SIMPLE_CATALOG_DELETED, SIMPLE_CATALOG_INDEX_DELETED, ODSN_CATALOG_CREATED, ODSN_CATALOG_INDEXED, ODSN_CATALOG_UPDATED, ODSN_CATALOG_INDEX_UPDATED, ODSN_CATALOG_DELETED, ODSN_CATALOG_INDEX_DELETED,

    // Dataset Operations
    SIMPLE_DATASET_CREATED, SIMPLE_DATASET_INDEXED, SIMPLE_DATASET_UPDATED, SIMPLE_DATASET_INDEX_UPDATED, SIMPLE_DATASET_DELETED, SIMPLE_DATASET_INDEX_DELETED, ODSN_DATASET_CREATED, ODSN_DATASET_INDEXED, ODSN_DATASET_UPDATED, ODSN_DATASET_INDEX_UPDATED, ODSN_DATASET_DELETED, ODSN_DATASET_INDEX_DELETED,

    // Search
    SIMPLE_DATASET_SEARCH_VERIFIED, ODSN_DATASET_FACETED_SEARCH_VERIFIED;
}
