default:
  image: ghcr.io/zazuko/deploy-image:v1.4
  tags:
    - kubernetes

stages:
  - build
  - push
  - deploy

# Configure `kubectl` to access the Kubernetes cluster
.configure-kubectl: &configure-kubectl
  - kubectl config set-cluster default "--server=${K8S_API_URL}" --insecure-skip-tls-verify=true
  # - kubectl config set-cluster default "--server=${K8S_API_URL}" "--certificate-authority=${K8S_CERTIFICATE_FILE}"
  - kubectl config set-credentials default "--token=${K8S_TOKEN}"
  - kubectl config set-context default --cluster=default --namespace=piveau-previews --user=default
  - kubectl config use-context default

# Build Docker image
build:
  stage: build

  artifacts:
    expire_in: 1 hour
    paths:
      - image.tar

  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      executor \
        --context="$CI_PROJECT_DIR" \
        --dockerfile=Dockerfile \
        --destination="$CI_REGISTRY_IMAGE" \
        --build-arg="BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg="COMMIT=$CI_COMMIT_SHA" \
        --build-arg="VERSION=$CI_COMMIT_REF_SLUG" \
        --no-push \
        --tarPath="$CI_PROJECT_DIR/image.tar"

# Push Docker image
push:
  stage: push

  needs:
    - job: build
      artifacts: true

  variables: # We don't need the sources for that
    GIT_STRATEGY: none

  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - gitlab-docker-push image.tar "$CI_REGISTRY_IMAGE"

# Deploy preview to the Kubernetes cluster
deploy-preview:
  stage: deploy
  script:
    - *configure-kubectl
    - cd k8s/
    - set-ingress-host piveau-ln-preview.zazukoians.org "${CI_ENVIRONMENT_SLUG}.piveau-ln-preview.zazukoians.org"
    - set-gitlab-annotations
    - kustomize edit set nameprefix "${CI_ENVIRONMENT_SLUG}-"
    - |
      kustomize edit add patch --patch "$(cat <<EOF
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: piveau-ui
      spec:
        tls:
          - secretName: ${CI_ENVIRONMENT_SLUG}-piveau-ln-preview-zazukoians-org-tls
      EOF
      )"
    - kustomize edit set image "${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}"
    - kustomize edit set label "app.kubernetes.io/instance:${CI_ENVIRONMENT_SLUG}"
    - kustomize build | tee manifest.yaml
    - kubectl apply -f manifest.yaml
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.piveau-ln-preview.zazukoians.org
    on_stop: remove-preview
    auto_stop_in: 3 weeks
    kubernetes:
      namespace: piveau-previews
  only:
    - branches
  except:
    - main

# Remove the preview deployment
remove-preview:
  stage: deploy
  script:
    - *configure-kubectl
    - cd k8s/
    - kustomize edit set nameprefix "${CI_ENVIRONMENT_SLUG}-"
    - |
      kustomize edit add patch --patch "$(cat <<EOF
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: piveau-ui
      spec:
        tls:
          - secretName: ${CI_ENVIRONMENT_SLUG}-piveau-ln-preview-zazukoians-org-tls
      EOF
      )"
    - kustomize edit set label "app.kubernetes.io/instance:${CI_ENVIRONMENT_SLUG}"
    - kustomize build | tee manifest.yaml
    - kubectl delete -f manifest.yaml
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    action: stop
    url: https://$CI_ENVIRONMENT_SLUG.piveau-ln-preview.zazukoians.org
    kubernetes:
      namespace: piveau-previews
  when: manual
  except:
    - main
