name: "Script Trigger Workflow"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - "REF"
          - "ABN"
        default: "REF"

      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - "HARVEST"
          - "HARVEST_SHOWCASES"
          - "CATALOGUES"
          - "DELETE_CATALOGUES"
          - "VOCABULARIES"
          - "DELETE_VOCABULARIES"
          - "TRIGGERS"
          - "METRICS"
          - "ORGANIZATIONS"
          - "DELETE_ORGANIZATIONS"
        default: "HARVEST"

      arguments:
        description: "Additional arguments (optional)"
        required: false
        type: string
        default: ""

jobs:
  workflow:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure no old .env file exists
        working-directory: ./opendata.swiss/metadata
        run: rm -f .env

      - name: Generate .env file (REF)
        if: ${{ github.event.inputs.environment == 'REF' }}
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
          echo "PIVEAU_METRICS_CACHE_ENDPOINT=${PIVEAU_METRICS_CACHE_ENDPOINT}" >> .env
          echo "PIVEAU_METRICS_CACHE_API_KEY=${PIVEAU_METRICS_CACHE_API_KEY}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_REF }}
          HUB_REPO_ENDPOINT: ${{ vars.HUB_REPO_ENDPOINT_REF }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ vars.CONSUS_SCHEDULING_ENDPOINT_REF }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_REF }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_REF }}
          PIVEAU_METRICS_CACHE_ENDPOINT: ${{ vars.PIVEAU_METRICS_CACHE_ENDPOINT_REF }}
          PIVEAU_METRICS_CACHE_API_KEY: ${{ secrets.PIVEAU_METRICS_CACHE_API_KEY_REF }}

      - name: Generate .env file (ABN)
        if: ${{ github.event.inputs.environment == 'ABN' }}
        working-directory: ./opendata.swiss/metadata
        run: |
          echo "PIVEAU_HUB_API_KEY=${PIVEAU_HUB_API_KEY}" >> .env
          echo "HUB_REPO_ENDPOINT=${HUB_REPO_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_ENDPOINT=${CONSUS_SCHEDULING_ENDPOINT}" >> .env
          echo "CONSUS_SCHEDULING_USERNAME=${CONSUS_SCHEDULING_USERNAME}" >> .env
          echo "CONSUS_SCHEDULING_PASSWORD=${CONSUS_SCHEDULING_PASSWORD}" >> .env
          echo "PIVEAU_METRICS_CACHE_ENDPOINT=${PIVEAU_METRICS_CACHE_ENDPOINT}" >> .env
          echo "PIVEAU_METRICS_CACHE_API_KEY=${PIVEAU_METRICS_CACHE_API_KEY}" >> .env
        env:
          PIVEAU_HUB_API_KEY: ${{ secrets.PIVEAU_HUB_API_KEY_ABN }}
          HUB_REPO_ENDPOINT: ${{ vars.HUB_REPO_ENDPOINT_ABN }}
          CONSUS_SCHEDULING_ENDPOINT: ${{ vars.CONSUS_SCHEDULING_ENDPOINT_ABN }}
          CONSUS_SCHEDULING_USERNAME: ${{ secrets.CONSUS_SCHEDULING_USERNAME_ABN }}
          CONSUS_SCHEDULING_PASSWORD: ${{ secrets.CONSUS_SCHEDULING_PASSWORD_ABN }}
          PIVEAU_METRICS_CACHE_ENDPOINT: ${{ vars.PIVEAU_METRICS_CACHE_ENDPOINT_ABN }}
          PIVEAU_METRICS_CACHE_API_KEY: ${{ secrets.PIVEAU_METRICS_CACHE_API_KEY_ABN }}

      - name: Run the selected action
        working-directory: ./opendata.swiss/metadata
        run: |
          if [ "${{ github.event.inputs.action }}" == "HARVEST" ]; then
            ./scripts/harvest.sh "${{ github.event.inputs.arguments }}";
          elif [ "${{ github.event.inputs.action }}" == "HARVEST_SHOWCASES" ]; then
            ./scripts/harvest_showcases.sh;
          elif [ "${{ github.event.inputs.action }}" == "CATALOGUES" ]; then
            ./scripts/catalogues.sh "${{ github.event.inputs.arguments }}";
          elif [ "${{ github.event.inputs.action }}" == "DELETE_CATALOGUES" ]; then
            ./scripts/catalogues_delete.sh "${{ github.event.inputs.arguments }}";
          elif [ "${{ github.event.inputs.action }}" == "VOCABULARIES" ]; then
            ./scripts/vocabularies.sh;
          elif [ "${{ github.event.inputs.action }}" == "DELETE_VOCABULARIES" ]; then
            ./scripts/vocabularies_delete.sh;
          elif [ "${{ github.event.inputs.action }}" == "TRIGGERS" ]; then
            ./scripts/triggers.sh;
          elif [ "${{ github.event.inputs.action }}" == "METRICS" ]; then
            ./scripts/metrics.sh;
          elif [ "${{ github.event.inputs.action }}" == "ORGANIZATIONS" ]; then
            ./scripts/organizations.sh "${{ github.event.inputs.arguments }}";
          elif [ "${{ github.event.inputs.action }}" == "DELETE_ORGANIZATIONS" ]; then
            ./scripts/organizations_delete.sh "${{ github.event.inputs.arguments }}";
          else
            echo "Unknown action: ${{ github.event.inputs.action }}";
            exit 1;
          fi
