name: "[UI] Tests"

on:
  push:
    paths:
      - "opendata.swiss/ui/**"
      - ".github/workflows/test-ui.yaml" # Trigger also if this workflow file is changed

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - run: npm ci
        working-directory: opendata.swiss/ui
      - run: npm run lint
        working-directory: opendata.swiss/ui

  typecheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - run: npm ci
        working-directory: opendata.swiss/ui
      - run: npm run typecheck
        working-directory: opendata.swiss/ui

  api-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Checkout CMS repository
        if: github.event.action != 'closed'
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.CMS_REPO_TEST }}
          path: opendata.swiss/ui/content

      - name: Prepare piveau backend env
        working-directory: opendata.swiss/metadata
        run: cp .env.example .env

      - name: Prepare env for ES
        run: |
          sudo sysctl -w vm.max_map_count=262144
          mkdir -p volumes/{graphdb,elasticsearch}-data
          sudo chown -R 1000:1000 ./volumes/elasticsearch-data
          sudo chmod -R 755 ./volumes/elasticsearch-data

      - name: Start elasticsearch
        run: docker compose -f docker-compose.yaml -f docker-compose.ci.yaml up -d elasticsearch
        working-directory: opendata.swiss/metadata

      - name: Start other services
        run: docker compose -f docker-compose.yaml -f docker-compose.ci.yaml up -d listmonk-app listmonk-init mailpit piveau-hub-repo graphdb graphdb-create-repo piveau-metrics-validating-shacl piveau-hub-search
        working-directory: opendata.swiss/metadata
        env:
          PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA: ${{ secrets.PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA }}

      - uses: fabasoad/setup-prolog-action@v1

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        working-directory: opendata.swiss/ui

      - run: . ../metadata/listmonk/install.sh; npm run dev > ui.log 2>&1 &
        working-directory: opendata.swiss/ui
        env:
          NUXT_API_TUNER_TESTS: true
          NUXT_LISTMONK_API_URL: http://localhost:9000/
          NUXT_LISTMONK_API_USER: admin-api
          NUXT_HYVOR_WEBHOOKS_ENABLED: true
          LOG_CONFIG: true
          NUXT_PUBLIC_PIVEAU_HUB_REPO_URL: http://localhost:8081/

      - run: npx wait-on http://localhost:3000 -t 30s
        working-directory: opendata.swiss/ui

      - run: npm run test:api -- --silent
        working-directory: opendata.swiss/ui
        shell: bash
        env:
          HUB_REPO_API_KEY: ${{ secrets.HUB_REPO_API_KEY }}

      - name: Collect app logs
        if: failure()
        run: |
          docker compose logs --no-log-prefix piveau-hub-repo > hub-repo.log
          docker compose logs --no-log-prefix mailpit > mailpit.log
          docker compose logs --no-log-prefix elasticsearch > elasticsearch.log
          docker compose logs --no-log-prefix piveau-hub-search > piveau-hub-search.log
          docker compose logs --no-log-prefix listmonk-app > listmonk-app.log
          docker compose logs --no-log-prefix listmonk-init > listmonk-init.log
        working-directory: opendata.swiss/metadata

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ui-test-results
          path: |
            opendata.swiss/metadata/listmonk/install.sh
            opendata.swiss/metadata/*.log
            opendata.swiss/ui/ui.log

  mocha-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Prepare piveau backend env
        working-directory: opendata.swiss/metadata
        run: cp .env.example .env

      - name: Start listmonk
        run: docker compose up -d listmonk-app listmonk-init mailpit
        working-directory: opendata.swiss/metadata

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        working-directory: opendata.swiss/ui

      - run: npm run test:mocha
        working-directory: opendata.swiss/ui
        shell: bash
